/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BangRouteImport } from './routes/bang'
import { Route as CeRouteImport } from './routes/ce'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaiRouteImport } from './routes/pai'
import { Route as QianRouteImport } from './routes/qian'
import { Route as ShiRouteImport } from './routes/shi'
import { Route as WallRouteImport } from './routes/wall'
import { Route as YiRouteImport } from './routes/yi'
import { Route as NbtiCodeRouteImport } from './routes/nbti.$code'
import { Route as WCodeRouteImport } from './routes/w.$code'
import { Route as XiangIdRouteImport } from './routes/xiang.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BangRoute = BangRouteImport.update({
  id: '/bang',
  path: '/bang',
  getParentRoute: () => rootRouteImport,
} as any)
const CeRoute = CeRouteImport.update({
  id: '/ce',
  path: '/ce',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiRoute = PaiRouteImport.update({
  id: '/pai',
  path: '/pai',
  getParentRoute: () => rootRouteImport,
} as any)
const QianRoute = QianRouteImport.update({
  id: '/qian',
  path: '/qian',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiRoute = ShiRouteImport.update({
  id: '/shi',
  path: '/shi',
  getParentRoute: () => rootRouteImport,
} as any)
const WallRoute = WallRouteImport.update({
  id: '/wall',
  path: '/wall',
  getParentRoute: () => rootRouteImport,
} as any)
const YiRoute = YiRouteImport.update({
  id: '/yi',
  path: '/yi',
  getParentRoute: () => rootRouteImport,
} as any)
const NbtiCodeRoute = NbtiCodeRouteImport.update({
  id: '/nbti/$code',
  path: '/nbti/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const WCodeRoute = WCodeRouteImport.update({
  id: '/w/$code',
  path: '/w/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const XiangIdRoute = XiangIdRouteImport.update({
  id: '/xiang/$id',
  path: '/xiang/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bang': typeof BangRoute
  '/ce': typeof CeRoute
  '/login': typeof LoginRoute
  '/pai': typeof PaiRoute
  '/qian': typeof QianRoute
  '/shi': typeof ShiRoute
  '/wall': typeof WallRoute
  '/yi': typeof YiRoute
  '/nbti/$code': typeof NbtiCodeRoute
  '/w/$code': typeof WCodeRoute
  '/xiang/$id': typeof XiangIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bang': typeof BangRoute
  '/ce': typeof CeRoute
  '/login': typeof LoginRoute
  '/pai': typeof PaiRoute
  '/qian': typeof QianRoute
  '/shi': typeof ShiRoute
  '/wall': typeof WallRoute
  '/yi': typeof YiRoute
  '/nbti/$code': typeof NbtiCodeRoute
  '/w/$code': typeof WCodeRoute
  '/xiang/$id': typeof XiangIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bang': typeof BangRoute
  '/ce': typeof CeRoute
  '/login': typeof LoginRoute
  '/pai': typeof PaiRoute
  '/qian': typeof QianRoute
  '/shi': typeof ShiRoute
  '/wall': typeof WallRoute
  '/yi': typeof YiRoute
  '/nbti/$code': typeof NbtiCodeRoute
  '/w/$code': typeof WCodeRoute
  '/xiang/$id': typeof XiangIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bang'
    | '/ce'
    | '/login'
    | '/pai'
    | '/qian'
    | '/shi'
    | '/wall'
    | '/yi'
    | '/nbti/$code'
    | '/w/$code'
    | '/xiang/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bang'
    | '/ce'
    | '/login'
    | '/pai'
    | '/qian'
    | '/shi'
    | '/wall'
    | '/yi'
    | '/nbti/$code'
    | '/w/$code'
    | '/xiang/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/bang'
    | '/ce'
    | '/login'
    | '/pai'
    | '/qian'
    | '/shi'
    | '/wall'
    | '/yi'
    | '/nbti/$code'
    | '/w/$code'
    | '/xiang/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BangRoute: typeof BangRoute
  CeRoute: typeof CeRoute
  LoginRoute: typeof LoginRoute
  PaiRoute: typeof PaiRoute
  QianRoute: typeof QianRoute
  ShiRoute: typeof ShiRoute
  WallRoute: typeof WallRoute
  YiRoute: typeof YiRoute
  NbtiCodeRoute: typeof NbtiCodeRoute
  WCodeRoute: typeof WCodeRoute
  XiangIdRoute: typeof XiangIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bang': {
      id: '/bang'
      path: '/bang'
      fullPath: '/bang'
      preLoaderRoute: typeof BangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ce': {
      id: '/ce'
      path: '/ce'
      fullPath: '/ce'
      preLoaderRoute: typeof CeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pai': {
      id: '/pai'
      path: '/pai'
      fullPath: '/pai'
      preLoaderRoute: typeof PaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qian': {
      id: '/qian'
      path: '/qian'
      fullPath: '/qian'
      preLoaderRoute: typeof QianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shi': {
      id: '/shi'
      path: '/shi'
      fullPath: '/shi'
      preLoaderRoute: typeof ShiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wall': {
      id: '/wall'
      path: '/wall'
      fullPath: '/wall'
      preLoaderRoute: typeof WallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yi': {
      id: '/yi'
      path: '/yi'
      fullPath: '/yi'
      preLoaderRoute: typeof YiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nbti/$code': {
      id: '/nbti/$code'
      path: '/nbti/$code'
      fullPath: '/nbti/$code'
      preLoaderRoute: typeof NbtiCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$code': {
      id: '/w/$code'
      path: '/w/$code'
      fullPath: '/w/$code'
      preLoaderRoute: typeof WCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xiang/$id': {
      id: '/xiang/$id'
      path: '/xiang/$id'
      fullPath: '/xiang/$id'
      preLoaderRoute: typeof XiangIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BangRoute: BangRoute,
  CeRoute: CeRoute,
  LoginRoute: LoginRoute,
  PaiRoute: PaiRoute,
  QianRoute: QianRoute,
  ShiRoute: ShiRoute,
  WallRoute: WallRoute,
  YiRoute: YiRoute,
  NbtiCodeRoute: NbtiCodeRoute,
  WCodeRoute: WCodeRoute,
  XiangIdRoute: XiangIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
